#build:
#    environment:
#        php:
#            version: 5.6
#before_commands:
#    - "composer self-update"
#    - "composer install --prefer-source --dev"
tools:
    external_code_coverage:
        timeout: 300
    php_sim:
        enabled: true
        min_mass: 16
        filter:
            excluded_paths:
                - 'app/*'
                - 'tests/*'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'app/*'
                - 'tests/*'
            paths: {  }
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'app/*'
                - 'tests/*'
            paths: {  }
        path_configs: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'app/*'
                - 'tests/*'
            paths: {  }
filter:
    excluded_paths:
        - 'app/*'
        - 'tests/*'
    paths: {  }
build_failure_conditions: {  }