filter:
    excluded_paths:
        - 'app/*'
        - 'tests/*'
        - 'ansible/*'
        - 'public/*'
        - 'src/Phansible/Resources/ansible'

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_mess_detector: true
    external_code_coverage: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cpd: true
    php_sim:
        enabled: true
        min_mass: 16
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
    php_analyzer:
        enabled: true
        extensions:
            - php
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
    sensiolabs_security_checker: true
