language: php
php:
   - 5.5
   - 5.6
before_install:
   - composer self-update
install:
   - composer install --no-interaction
   - php vendor/autoload.php
script:
   - mkdir -p build/logs
   - php vendor/bin/phpunit -c tests/phpunit.xml
after_script:
   - php vendor/bin/coveralls
