phansible_default:
    path: /
    defaults: { _controller: "Phansible\Controller\DefaultController::indexAction" }

phansible_about:
    path: /about
    defaults: { _controller: "Phansible\Controller\DefaultController::aboutAction" }

phansible_docs:
    path: /docs/{doc}
    defaults: { _controller: "Phansible\Controller\DefaultController::docsAction" }

phansible_bundle:
    path: /generate
    defaults: { _controller: "Phansible\Controller\BundleController::indexAction" }