twig.path: "%root_dir%/src/Phansible/Resources/views"
#http_cache.cache_dir: "%root_dir%/app/cache/http"
routing.resource: "%root_dir%/app/config/routing.yml"

debug: true

#bundle generator options
config:
  boxes:
    lucid32:
      name: Ubuntu Lucid Lynx 32
      url: http://files.vagrantup.com/lucid32.box
    lucid64:
      name: Ubuntu Lucid Lynx 64
      url: http://files.vagrantup.com/lucid64.box
    precise32:
      name: Ubuntu Precise Pangolin 32
      url: http://files.vagrantup.com/precise32.box
    precise64:
      name: Ubuntu Precise Pangolin 64
      url: http://files.vagrantup.com/precise64.box

  syspackages:
    - curl
    - vim

  phppackages:
    - php5-cli
    - php-pear
    - php5-curl
    - php5-mysql