twig.path: "%root_dir%/src/Phansible/Resources/views"
ansible.path: "%root_dir%/src/Phansible/Resources/ansible"
ansible.templates: "%root_dir%/src/Phansible/Resources/ansible/templates"
routing.resource: "%root_dir%/app/config/routing.yml"
docs.path: "%root_dir%/src/Phansible/Resources/docs"

@import:
    - app/config/phansible/boxes.yml
    - app/config/phansible/webservers.yml
    - app/config/phansible/syspackages.yml
    - app/config/phansible/phppackages.yml
    - app/config/phansible/rabbitmqplugins.yml
    - app/config/phansible/databases.yml
    - app/config/phansible/workers.yml
    - app/config/phansible/peclpackages.yml
    - app/config/phansible/rolepackagemap.yml

config:
  bundles:
    - vagrant
    - webserver
    - php
    - database
    - workers
    - syspackages
    - timezone
