---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties
    - acl

- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ php_ppa }}

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install Extra Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: sys_packages

- name: Create directory if not existent
  sudo: yes
  file: path={{ project_root }} state=directory owner={{ system_user }} group={{ system_group }}

- name: Set system ACL mask
  shell: 'setfacl -Rn -m m:rwX {{ project_root }}'

- name: Set system user ACLs
  shell: 'setfacl -Rn -m u:"{{ system_user }}":rwX {{ project_root }}'

- name: Read ACLs for web_user
  shell: 'setfacl -Rn -m u:"{{ webserver_user }}":rX -m d:u:"{{ webserver_user }}":rX {{ project_root }}'

- name: Read and Write ACLs for shell user
  shell: 'setfacl -Rn -m u:"{{ system_user }}":rwX -m d:u:"{{ system_user }}":rwX {{ project_root }}'

- name: Read and Write ACLs cache dir
  shell: 'setfacl -Rn -m u:"{{ webserver_user }}":rwX -m d:u:"{{ webserver_user }}":rwX {{ project_root }}/app/cache'