phppackages:
  - php5-cli
  - php-pear
  - php5-curl
  - php5-imagick
  - php5-cgi
  - php5-common
  - php5-dbg
  - php5-enchant
  - php5-fpm
  - php5-gd
  - php5-geoip
  - php5-gmp
  - php5-imap
  - php5-interbase
  - php5-intl
  - php5-ldap
  - php5-mapscript
  - php5-mbstring
  - php5-mcrypt
  - php5-memcache
  - php5-memcached
  - php5-odbc
  - php5-pspell
  - php5-readline
  - php5-recode
  - php5-snmp
  - php5-sqlite
  - php5-svn
  - php5-sybase
  - php5-tidy
  - php5-xcache
  - php5-xdebug
  - php5-xmlrpc
  - php5-xsl