---
- hosts: all
  sudo: true
  vars:
    doc_root: /vagrant/web
    sys_packages: ["vim"]
    php_packages: ["php5-cli","php5-curl","php5-xdebug"]
    php_ppa: php5
    php_fpm_ini: /etc/php5/fpm/php.ini
    php_error_reporting: -1
    php_display_errors: 'On'
    php_display_startup_errors: 'On'
    php_html_errors: 'On'
  roles:
    - init
    - nginx
    - php5-fpm
    - composer
    - phpcommon
